import 'package:flutter/material.dart';

const _kBg = Color(0xFFC8DCF0);
const _kNavy = Color(0xFF1A3A5C);
const _kSubtitle = Color(0xFF4A6FA5);
const _kCardBg = Colors.white;
const _kBlue = Color(0xFF6BAED4);
const _kIconBg = Color(0xFFD6ECFA);
const _kHighlight = Color(0xFFD6ECFA);

class ReadMoreScreen extends StatefulWidget {
  final VoidCallback? onBack;

  const ReadMoreScreen({super.key, this.onBack});

  @override
  State<ReadMoreScreen> createState() => _ReadMoreScreenState();
}

class _ReadMoreScreenState extends State<ReadMoreScreen> {
  final List<String> _expandedItems = [];

  void _toggleExpand(String id) {
    setState(() {
      if (_expandedItems.contains(id)) {
        _expandedItems.remove(id);
      } else {
        _expandedItems.add(id);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _kBg,
      body: SafeArea(
        bottom: false,
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(20, 20, 20, 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // ── Header ───────────────────────────────────────────────────
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 16),
                decoration: BoxDecoration(
                  color: _kBlue,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Row(
                  children: [
                    GestureDetector(
                      onTap: widget.onBack ?? () {
                        if (Navigator.of(context).canPop()) {
                          Navigator.of(context).pop();
                        }
                      },
                      child: Container(
                        width: 34,
                        height: 34,
                        decoration: BoxDecoration(
                          color: Colors.white24,
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: const Icon(
                          Icons.arrow_back_ios_new_rounded,
                          color: Colors.white,
                          size: 16,
                        ),
                      ),
                    ),
                    const SizedBox(width: 10),
                    const Icon(
                      Icons.menu_book_rounded,
                      color: Colors.white,
                      size: 18,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: const [
                          Text(
                            'ReadMore',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                          Text(
                            'Learn more about your journey',
                            style: TextStyle(
                              color: Colors.white70,
                              fontSize: 11,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 28),

              // ── Top Card ─────────────────────────────────────────────
              Container(
                width: double.infinity,
                decoration: BoxDecoration(
                  color: _kCardBg,
                  borderRadius: BorderRadius.circular(24),
                  boxShadow: const [
                    BoxShadow(
                      color: Color(0x0C000000),
                      blurRadius: 10,
                      offset: Offset(0, 4),
                    ),
                  ],
                ),
                padding: const EdgeInsets.all(24),
                child: Column(
                  children: [
                    const Text(
                      'How Lumora Works 💙',
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.w800,
                        color: _kNavy,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Your guide to healing, growth & understanding',
                      style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w700,
                        color: _kNavy,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 20),
                    Container(
                      width: double.infinity,
                      decoration: BoxDecoration(
                        color: _kHighlight,
                        borderRadius: BorderRadius.circular(16),
                      ),
                      padding: const EdgeInsets.all(20),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Lumora helps you track your mood,\npractice mindful exercises, and build\nhealthy habits.',
                            style: TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.w700,
                              color: Color(0xFF1E63B3),
                              height: 1.5,
                            ),
                          ),
                          const SizedBox(height: 16),
                          _buildSparklePoint('Use CBT-based tools'),
                          const SizedBox(height: 8),
                          _buildSparklePoint('Do ERP exercises'),
                          const SizedBox(height: 8),
                          _buildSparklePoint('Grow step by step'),
                        ],
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 32),

              // ── Explore Topics ───────────────────────────────────────
              const Text(
                'Explore Topics',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w800,
                  color: _kNavy,
                ),
              ),
              const SizedBox(height: 16),

              // ── Accordions ───────────────────────────────────────────
              _buildAccordion(
                id: 'cbt',
                icon: Icons.psychology_outlined,
                title: 'Understanding CBT',
                isExpanded: _expandedItems.contains('cbt'),
                onToggle: () => _toggleExpand('cbt'),
                child: _buildCBTContent(),
              ),

              const SizedBox(height: 12),
              _buildAccordion(
                id: 'ocd',
                icon: Icons.show_chart_rounded,
                title: 'Understanding OCD',
                isExpanded: _expandedItems.contains('ocd'),
                onToggle: () => _toggleExpand('ocd'),
                child: _buildOCDContent(),
              ),
              const SizedBox(height: 12),
              _buildAccordion(
                id: 'depression',
                icon: Icons.cloud_queue_rounded,
                title: 'About Depression',
                isExpanded: _expandedItems.contains('depression'),
                onToggle: () => _toggleExpand('depression'),
                child: _buildDepressionContent(),
              ),
              const SizedBox(height: 12),
              _buildAccordion(
                id: 'anxiety',
                icon: Icons.favorite_border_rounded,
                title: 'Anxiety & Stress',
                isExpanded: _expandedItems.contains('anxiety'),
                onToggle: () => _toggleExpand('anxiety'),
                child: _buildAnxietyContent(),
              ),

              const SizedBox(height: 100),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSparklePoint(String text) {
    return Row(
      children: [
        const Text('✨', style: TextStyle(fontSize: 12)),
        const SizedBox(width: 8),
        Text(
          text,
          style: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w800,
            color: Color(0xFF1E63B3),
          ),
        ),
      ],
    );
  }

  Widget _buildDotPoint(String text) {
    return Row(
      children: [
        const Icon(Icons.circle, size: 4, color: _kSubtitle),
        const SizedBox(width: 8),
        Text(
          text,
          style: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w700,
            color: _kSubtitle,
          ),
        ),
      ],
    );
  }

  Widget _buildAnxietyContent() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        SizedBox(height: 16),
        Text('What is Anxiety?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Anxiety is a natural response to fear or danger. It becomes a problem when it is excessive, overwhelming, or interferes with daily life.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Symptoms of Anxiety', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Physical symptoms:', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        _buildDotPoint('Thumping heart (palpitations)'),
        SizedBox(height: 4),
        _buildDotPoint('Nausea'),
        SizedBox(height: 4),
        _buildDotPoint('Trembling'),
        SizedBox(height: 4),
        _buildDotPoint('Sweating'),
        SizedBox(height: 4),
        _buildDotPoint('Dry mouth'),
        SizedBox(height: 4),
        _buildDotPoint('Chest pain'),
        SizedBox(height: 4),
        _buildDotPoint('Headaches'),
        SizedBox(height: 4),
        _buildDotPoint('Fast breathing'),
        SizedBox(height: 4),
        _buildDotPoint('Dizziness'),
        SizedBox(height: 4),
        Text('These happen because the body releases stress hormones like adrenaline, triggering a "fight or flight" response.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Mental symptoms:', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        _buildDotPoint('Feeling tired'),
        SizedBox(height: 4),
        _buildDotPoint('Restlessness or irritability'),
        SizedBox(height: 4),
        _buildDotPoint('Difficulty concentrating or making decisions'),
        SizedBox(height: 4),
        _buildDotPoint('Trouble sleeping'),
        SizedBox(height: 4),
        _buildDotPoint('Constant worrying'),
        SizedBox(height: 4),
        SizedBox(height: 12),
        Text('Behavioral symptoms:', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        _buildDotPoint('Avoiding social situations'),
        SizedBox(height: 4),
        _buildDotPoint('Wanting to be alone'),
        SizedBox(height: 4),
        _buildDotPoint('Compulsive behaviors (e.g., excessive handwashing)'),
        SizedBox(height: 4),
        _buildDotPoint('Fear of leaving home (agoraphobia)'),
        SizedBox(height: 4),
        _buildDotPoint('Unhealthy coping (alcohol or substance use)'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Causes of Anxiety', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        _buildDotPoint('Genetics or brain chemical imbalance'),
        SizedBox(height: 4),
        _buildDotPoint('Past traumatic or difficult experiences'),
        SizedBox(height: 4),
        _buildDotPoint('Current stress or life events'),
        SizedBox(height: 4),
        _buildDotPoint('Medication side effects or substance use'),
        SizedBox(height: 4),
        _buildDotPoint('Other health conditions (e.g., hyperthyroidism)'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Is Anxiety Normal?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Anxiety is normal in stressful situations and can help you respond to danger.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('It becomes a disorder if it:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Is out of proportion'),
        SizedBox(height: 4),
        _buildDotPoint('Continues after stress has passed'),
        SizedBox(height: 4),
        _buildDotPoint('Happens without a clear reason'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Risk Factors', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        _buildDotPoint('Family history of mental health conditions'),
        SizedBox(height: 4),
        _buildDotPoint('Childhood abuse or neglect'),
        SizedBox(height: 4),
        _buildDotPoint('Bullying'),
        SizedBox(height: 4),
        _buildDotPoint('Loss or major life changes'),
        SizedBox(height: 4),
        _buildDotPoint('Unemployment'),
        SizedBox(height: 4),
        _buildDotPoint('Substance dependence'),
        SizedBox(height: 4),
        _buildDotPoint('Chronic physical illness'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Anxiety Disorders', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('An anxiety disorder occurs when symptoms interfere with daily life. About 1 in 20 people are affected. Types include:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Generalized anxiety disorder (GAD)'),
        SizedBox(height: 4),
        _buildDotPoint('Panic disorder'),
        SizedBox(height: 4),
        _buildDotPoint('Social anxiety'),
        SizedBox(height: 4),
        _buildDotPoint('Phobias (including agoraphobia)'),
        SizedBox(height: 4),
        _buildDotPoint('PTSD'),
        SizedBox(height: 4),
        _buildDotPoint('OCD'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Treatment for Anxiety', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Non-medication approaches:', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        _buildDotPoint('Understanding: Learning about anxiety helps reduce fear of symptoms'),
        SizedBox(height: 4),
        _buildDotPoint('Talking: Sharing with friends, family, or professionals'),
        SizedBox(height: 4),
        _buildDotPoint('Counselling: Helps with problem-solving'),
        SizedBox(height: 4),
        _buildDotPoint('Anxiety management courses: Teach coping and relaxation skills'),
        SizedBox(height: 4),
        _buildDotPoint('Cognitive Behavioral Therapy (CBT): Changes negative thought patterns'),
        SizedBox(height: 4),
        _buildDotPoint('Self-help: Relaxation techniques and stress management'),
        SizedBox(height: 4),
        SizedBox(height: 12),
        Text('Medication', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        Text('Sometimes used for severe anxiety, but usually short-term due to side effects and risk of dependence.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Alcohol and Anxiety', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        Text('Alcohol may give short-term relief but worsens anxiety over time and can lead to dependency.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('When to See a Doctor', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Seek help if:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Anxiety is hard to manage'),
        SizedBox(height: 4),
        _buildDotPoint('It affects your daily life'),
        SizedBox(height: 4),
        _buildDotPoint('Self-help methods are not working'),
        SizedBox(height: 4),
        Text('Professional support, including therapies like CBT, can be very effective.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('---', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
      ],
    );
  }

  Widget _buildDepressionContent() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        SizedBox(height: 16),
        Text('How to Deal with Mild Depression', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('There are many things you can do to manage mild depression, often called guided self-help. Advice can come from professionals, books, or trusted sources. Understanding your symptoms is the first step toward feeling better.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Don\'t Bottle It Up', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Avoid hiding your feelings or trying to "push through" depression alone. Suppressing emotions can make things worse. Being open with trusted friends or family can help you feel supported and understood.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Stay Active', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Depression can make you want to withdraw, but staying engaged is important.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Make a list of activities you enjoy'),
        SizedBox(height: 4),
        _buildDotPoint('Spend time with people'),
        SizedBox(height: 4),
        _buildDotPoint('Take part in simple activities'),
        SizedBox(height: 4),
        _buildDotPoint('Exercise regularly'),
        SizedBox(height: 4),
        Text('Even small steps, like walking or listening to music, can help improve your mood.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Make a Daily Plan', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Structure your day to stay motivated.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Include tasks and enjoyable activities'),
        SizedBox(height: 4),
        _buildDotPoint('Keep activities simple and manageable'),
        SizedBox(height: 4),
        _buildDotPoint('Tick off completed tasks'),
        SizedBox(height: 4),
        Text('Over time, this helps build a sense of achievement and routine.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Keep a Diary', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Track what you do each day and rate your enjoyment (1–10). This helps you:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('See progress'),
        SizedBox(height: 4),
        _buildDotPoint('Identify activities you enjoy'),
        SizedBox(height: 4),
        _buildDotPoint('Stay motivated'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Avoid Unhelpful Habits', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Some behaviors may feel helpful but worsen depression, such as:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Drinking alcohol'),
        SizedBox(height: 4),
        _buildDotPoint('Staying in bed too long'),
        SizedBox(height: 4),
        _buildDotPoint('Watching TV all day'),
        SizedBox(height: 4),
        Text('Try to reduce these and replace them with healthier activities.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Solve Problems Step by Step', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Problems can feel overwhelming, so:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Write the problem clearly'),
        SizedBox(height: 4),
        _buildDotPoint('Think of possible solutions (even unrealistic ones)'),
        SizedBox(height: 4),
        _buildDotPoint('Break solutions into small steps'),
        SizedBox(height: 4),
        _buildDotPoint('Complete one step at a time'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Understand the Vicious Cycle', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Depression can lower energy and motivation, leading to inactivity, guilt, and lower self-esteem—making depression worse. Recognizing this cycle helps you break it.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Recognize Negative Thinking', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Common patterns include:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Gloomy thoughts (feeling worthless)'),
        SizedBox(height: 4),
        _buildDotPoint('Catastrophizing (expecting the worst)'),
        SizedBox(height: 4),
        _buildDotPoint('Over-generalizing (drawing big conclusions from small events)'),
        SizedBox(height: 4),
        _buildDotPoint('Focusing on negatives'),
        SizedBox(height: 4),
        _buildDotPoint('Self-blame'),
        SizedBox(height: 4),
        _buildDotPoint('Mind-reading or predicting failure'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Break the Cycle', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Ask yourself:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('What happened?'),
        SizedBox(height: 4),
        _buildDotPoint('What did I think?'),
        SizedBox(height: 4),
        _buildDotPoint('What did I feel?'),
        SizedBox(height: 4),
        Text('Then challenge negative thoughts by balancing them with more positive or realistic ones.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Challenge Negative Beliefs', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('You may be overly critical of yourself. Treat yourself like you would a friend—look for evidence against negative beliefs and focus on your strengths.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Practice Mindfulness', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Mindfulness helps you stay present and manage thoughts.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Focus on your breathing'),
        SizedBox(height: 4),
        _buildDotPoint('Notice thoughts and feelings without judging'),
        SizedBox(height: 4),
        _buildDotPoint('Gently bring your attention back when distracted'),
        SizedBox(height: 4),
        Text('With practice, this can reduce the impact of negative thoughts.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('---', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
      ],
    );
  }

  Widget _buildCBTContent() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        SizedBox(height: 16),
        Text('What is Cognitive Behavioral Therapy?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('CBT is a type of talking therapy. Cognitive means the way we think about things. Cognitive therapy helps us to understand our thoughts so that we can think about things more positively.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('Behavioral therapy helps us to change any of our actions that cause us harm or are unhelpful (for example, staying at home all the time because of a fear of something outside).', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('Cognitive and behavioral therapies are often used together because how we behave often depends on how we think about certain things or situations.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Cognitive Therapy', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Our thoughts include our ideas, mental images, beliefs and attitudes. These are called cognitive processes. Cognitive therapy is designed to help you to understand your current thoughts.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('It can help you identify any harmful, unhelpful and false ideas or thoughts that you have. The aim is then to change the way you think so that you can avoid these ideas. Cognitive therapy helps your thought patterns to be more realistic and helpful.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Behavioral Therapy', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('This aims to change any behaviors that are harmful or not helpful. For example, a common unhelpful behavior is to avoid situations that can make you anxious.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('In some people with phobias the avoidance can affect day-to-day life. A type of behavioral therapy called exposure therapy may be used to help. This involves you being gradually exposed more and more to the feared situation.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('The therapist will show you how to control anxiety and how to cope when facing up to the feared situations.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('How Does Cognitive Behavioral Therapy Work?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Cognitive behavioral therapy (CBT) can help you make sense of difficult problems by breaking them down into smaller parts. In CBT, problems are broken down into five main areas:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Situations'),
        SizedBox(height: 4),
        _buildDotPoint('Thoughts'),
        SizedBox(height: 4),
        _buildDotPoint('Emotions'),
        SizedBox(height: 4),
        _buildDotPoint('Physical feelings'),
        SizedBox(height: 4),
        _buildDotPoint('Actions'),
        SizedBox(height: 4),
        Text('CBT is based on the idea that these five areas affect each other. For example, your thoughts about a certain situation can often affect how you feel physically and emotionally, as well as how you act in response. CBT helps you to identify specific problems so that you can try to solve them, and helps you to develop coping skills.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Stopping Negative Thought Cycles', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('There are helpful and unhelpful ways of reacting to a situation. Some thoughts, feelings, physical sensations and actions can trap you in a negative cycle and even create new situations that make you feel worse about yourself. This can make you feel hopeless, lonely, depressed and tired. You may become trapped in a negative cycle, sitting at home alone and feeling bad about yourself.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('CBT aims to stop negative cycles such as these by breaking down the things that make you feel bad, anxious or scared. By making your problems more manageable, CBT can help you change your negative thought patterns and improve the way you feel.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Which Conditions Can Be Helped Using Cognitive Behavioral Therapy?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('CBT has been shown to help people with many different conditions - both mental health conditions and physical conditions. For example:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Certain anxiety disorders, including phobias, panic attacks and panic disorder'),
        SizedBox(height: 4),
        _buildDotPoint('Depression'),
        SizedBox(height: 4),
        _buildDotPoint('Eating disorders - for example, bulimia nervosa'),
        SizedBox(height: 4),
        _buildDotPoint('OCD'),
        SizedBox(height: 4),
        _buildDotPoint('Body dysmorphic disorder'),
        SizedBox(height: 4),
        _buildDotPoint('Anger'),
        SizedBox(height: 4),
        _buildDotPoint('Post-traumatic stress disorder'),
        SizedBox(height: 4),
        _buildDotPoint('Sexual and relationship problems'),
        SizedBox(height: 4),
        _buildDotPoint('Habits such as facial tics'),
        SizedBox(height: 4),
        _buildDotPoint('Drug or alcohol misuse'),
        SizedBox(height: 4),
        _buildDotPoint('Some sleep problems'),
        SizedBox(height: 4),
        _buildDotPoint('Chronic fatigue syndrome/myalgic encephalomyelitis (CFS/ME)'),
        SizedBox(height: 4),
        _buildDotPoint('Persistent (chronic) pain'),
        SizedBox(height: 4),
        _buildDotPoint('Irritable bowel syndrome'),
        SizedBox(height: 4),
        _buildDotPoint('Post-traumatic stress disorder (PTSD)'),
        SizedBox(height: 4),
        SizedBox(height: 16),
        Text('Benefits of CBT', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('CBT can help people cope better with their symptoms. As a rule, the more specific the problem, the more likely that CBT may help. This is because it is a practical therapy which focuses on particular problems and aims to overcome them.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('CBT is sometimes used as the only treatment and sometimes used in addition to medication, depending on the type and severity of the condition being treated.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('The emphasis on cognitive or behavioral aspects of therapy can vary, depending on the condition being treated. For example, there is often more emphasis on behavioral therapy when treating OCD - where repetitive compulsive actions are often one of the main problems. The emphasis may be on cognitive therapy for other situations - for example, when treating depression.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('How Do I Make Progress?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('After working out what you can change, your therapist will ask you to practice these changes in your daily life. This may involve:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Questioning upsetting thoughts and replacing them with more helpful ones'),
        SizedBox(height: 4),
        _buildDotPoint('Recognizing when you\'re going to do something that will make you feel worse and to be able to do something more helpful instead'),
        SizedBox(height: 4),
        Text('At each session, you\'ll discuss with your therapist how you\'ve got on with putting the changes into practice and what it felt like. Your therapist will be able to make other suggestions to help you.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('Confronting fears and anxieties can be very difficult. Your therapist won\'t ask you to do things you don\'t want to do and will only work at a pace you\'re comfortable with.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('What About Cognitive Behavioral Therapy Without a Therapist?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Although CBT often works best with the help of a trained therapist, some people prefer to tackle their problems themselves. For some people, self-help therapy can be as effective as CBT with a therapist.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('If you have an assessment through the national NHS system Improving Access to Psychological Therapies (IAPT), your counsellor may suggest one of these treatments. Otherwise, it\'s still very important to see your doctor to make sure CBT is right for you.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Self-help books', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        Text('There are many self-help books available. Some are excellent, but many are not. If in doubt look for self-help books that have been recommended by a professional organization or by a health professional. For example:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('\'Overcoming\' self-help books. In the UK, the Royal College of Psychiatrists endorses the Overcoming self-help series. These books and CDs are based on CBT and cover more than 30 common mental health problems. Titles include \'Overcoming Anxiety\', \'Overcoming Low Self-esteem\' and \'Overcoming Grief\'. They are available from bookshops and libraries. You can also download them from the Overcoming.co.uk website.'),
        SizedBox(height: 4),
        _buildDotPoint('Books on Prescription. You can also find NHS-endorsed books for common emotional and mental health problems on the \'Reading Well Books on Prescription\' website.'),
        SizedBox(height: 4),
        SizedBox(height: 12),
        Text('Online mental health services', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        Text('In the UK, some online mental health services have been approved for use by the NHS. Research shows that these can be just as effective as face-to-face therapy with a therapist for depression, anxiety and other mental health problems.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('The kind of support offered by online mental health services varies. Some allow you to work through a self-help course online with support from a health professional. Others offer live therapy with a therapist via instant messaging or a webcam.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('You can also join an anonymous online community where you can meet and interact with other people who have similar mental health problems to you. You don\'t need much experience with computers or technology to use them.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Phone and email CBT', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        Text('Phone and email CBT can be ideal if you\'re shy or don\'t want to meet the therapist, or if you can\'t find one in your area. They save travelling time, can avoid the problem of finding childcare and are available during evenings and weekends.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('Phone or email CBT is just like having a face-to-face session, except that you talk to a trained therapist over the phone. Phone and email CBT are increasingly being offered by private therapists and sometimes by workplaces and charities.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Computerized CBT', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        Text('There are a number of interactive programs available that allow you to benefit from CBT with little or no contact with a therapist.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('In the UK, Beating the Blues (beatingtheblues.co.uk) is approved for treating mild-to-moderate depression. However, there are many similar computerized CBT packages that may also be effective. Some people prefer using a computer rather than talking to a therapist about their private feelings.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('However, you may still benefit from occasional meetings or phone calls with a therapist to guide you and to monitor your progress.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 12),
        Text('Computerized CBT for young people', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: _kNavy)),
        SizedBox(height: 6),
        Text('Several forms of digital CBT, using computers, tablets or phone, have been designed specifically for young people. They have been developed to help with relaxation, dealing with strong emotions, problem solving, mindfulness, communicating and interacting with other people.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('They can also work in the same way as more \'traditional\' CBT, but helping young people to identify unhelpful or negative thoughts and challenge them.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('They are now recommended by the National Institute for Health and Care Excellence (NICE) as one of the first-line treatments for young people aged 5-18 years who have mild depression.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('---', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
      ],
    );
  }

  Widget _buildOCDContent() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        SizedBox(height: 16),
        Text('What is OCD?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Obsessive-compulsive disorder (OCD) is a mental health problem. Symptoms typically include recurring thoughts and repetitive behaviors in response to the recurring thoughts. A common example is recurring unwanted thoughts about germs and dirt, with a need to wash your hands repeatedly to \'clean off the germs\'. This can be not only very distressing, but also very time-consuming and intrusive in daily life.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('What Are Obsessions?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Obsessions are unpleasant thoughts, mental images or urges that keep coming into your mind. Obsessions are not simply worries about your life problems. Common obsessions include:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Fears about contamination with dirt, germs, viruses (for example, HIV), etc.'),
        SizedBox(height: 4),
        _buildDotPoint('Worries about doors being unlocked, fires left on, causing harm to someone, etc.'),
        SizedBox(height: 4),
        _buildDotPoint('Intrusive thoughts or images of swearing, blasphemy, sex, someone harmed, etc.'),
        SizedBox(height: 4),
        _buildDotPoint('Fear of making a mistake or behaving badly'),
        SizedBox(height: 4),
        _buildDotPoint('A need for exactness in how you order or arrange things'),
        SizedBox(height: 4),
        _buildDotPoint('A need to collect things that others might throw away (hoarding)'),
        SizedBox(height: 4),
        Text('These are examples. Obsessions can be about all sorts of things. Obsessive thoughts can make you feel anxious or disgusted. You normally try to ignore or suppress obsessive thoughts; for example, you may try to think other thoughts to neutralize the obsession.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('What Are Compulsions?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Compulsions are thoughts or actions that you feel you must do or repeat. Usually, the compulsive act is in response to an obsession. A compulsion is a way of trying to deal with the distress or anxiety caused by an obsession.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('For example, you may wash your hands every few minutes in response to an obsessional fear about germs. Another example is you may keep on checking that doors are locked, in response to the obsession about doors being unlocked. Other compulsions include repeated cleaning, counting, touching, saying words silently, arranging and organizing - but there are others.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('How Does Obsessive-Compulsive Disorder Affect Your Life?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('Obsessive-compulsive disorder (OCD) involves repeated unwanted thoughts (obsessions) that cause anxiety and distress. To reduce this feeling, people perform certain actions or rituals (compulsions), but the relief is only temporary, and the cycle keeps repeating.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('The impact of OCD can vary. Some people experience mild disruption, while others may spend a lot of time on compulsions, making it difficult to carry out daily activities or focus on important tasks. Even though they understand their thoughts and behaviors are excessive, they often feel unable to control them.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('OCD can affect work or school, relationships, social life, and overall quality of life. Some people carry out their compulsions in secret, while others may appear to function normally but feel distressed internally due to constant intrusive thoughts.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('Many people hide their symptoms because of fear or shame, especially if their thoughts feel disturbing or embarrassing. This can sometimes lead to feelings of isolation or depression. However, OCD is not your fault, and with the right support and treatment, it can be managed effectively.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('What Causes OCD?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('The cause of OCD is not clear. Slight changes in the balance of some brain chemicals (neurotransmitters) such as serotonin may play a role. This is why medication is thought to help.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('Also, the chance of developing OCD is higher than average if you have a first-degree family member who is affected (mother, father, brother, sister, child). So, there may be some genetic element to OCD. However, so far, no genes have been found to be linked with OCD.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('Other theories about the cause of OCD have been suggested but none proved.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('Who Gets Obsessive-Compulsive Disorder?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('It is thought that between 1 to 3 in 100 adults have OCD. Anyone at any age can develop OCD but it usually first develops between the ages of 18 and 30. Up to 2 in 100 children are also thought to have OCD.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        Text('OCD is usually a persistent condition. This means it tends not to be cured, but you learn ways to manage it.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('How Is Obsessive-Compulsive Disorder Diagnosed?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('If you are concerned that you may have OCD, you should see your doctor and explain your concerns. They may start by asking some of the following questions. These questions can act as a screen for possible OCD:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Do you wash or clean a lot?'),
        SizedBox(height: 4),
        _buildDotPoint('Do you check things a lot?'),
        SizedBox(height: 4),
        _buildDotPoint('Is there any thought that keeps bothering you that you would like to get rid of but cannot?'),
        SizedBox(height: 4),
        _buildDotPoint('Do your daily activities take a long time to finish?'),
        SizedBox(height: 4),
        _buildDotPoint('Are you concerned about putting things in a special order, or are you upset by mess?'),
        SizedBox(height: 4),
        _buildDotPoint('Do these problems trouble you?'),
        SizedBox(height: 4),
        Text('A more detailed assessment is then needed for OCD to be diagnosed. This may either be carried out by your doctor or by a specialist mental health professional. The assessment will look at any obsessional thoughts and compulsions that you have and how they affect you and your daily life. Children with OCD may be referred to a specialist mental health team which is experienced in assessing and treating children with OCD.', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        SizedBox(height: 16),
        Text('What Is the Treatment for Obsessive-Compulsive Disorder?', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: _kNavy)),
        SizedBox(height: 8),
        Text('The usual treatment for OCD is:', style: TextStyle(fontSize: 13, color: _kSubtitle, height: 1.5)),
        SizedBox(height: 8),
        _buildDotPoint('Cognitive behavioural therapy (CBT)'),
        SizedBox(height: 4),
        _buildDotPoint('Medication, usually with a selective serotonin reuptake inhibitor (SSRI) antidepressant medicine'),
        SizedBox(height: 4),
        _buildDotPoint('A combination of CBT plus an SSRI antidepressant medicine'),
        SizedBox(height: 4),
      ],
    );
  }


  Widget _buildAccordion({
    required String id,
    required IconData icon,
    required String title,
    required bool isExpanded,
    required VoidCallback onToggle,
    required Widget child,
  }) {
    return GestureDetector(
      onTap: onToggle,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        decoration: BoxDecoration(
          color: _kCardBg,
          borderRadius: BorderRadius.circular(24),
          boxShadow: const [
            BoxShadow(
              color: Color(0x08000000),
              blurRadius: 8,
              offset: Offset(0, 3),
            ),
          ],
        ),
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  width: 44,
                  height: 44,
                  decoration: BoxDecoration(
                    color: _kIconBg,
                    borderRadius: BorderRadius.circular(14),
                  ),
                  child: Icon(icon, color: _kSubtitle, size: 24),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Text(
                    title,
                    style: const TextStyle(
                      fontSize: 15,
                      fontWeight: FontWeight.w800,
                      color: _kNavy,
                    ),
                  ),
                ),
                Icon(
                  isExpanded ? Icons.keyboard_arrow_up_rounded : Icons.keyboard_arrow_down_rounded,
                  color: _kBlue,
                  size: 24,
                ),
              ],
            ),
            if (isExpanded) ...[
              const SizedBox(height: 20),
              child,
            ],
          ],
        ),
      ),
    );
  }
}
